### ISSUE TITLE
Needs to migrate to the ACE editor which replaced Orion

### ISSUE THREAD

**Issue by knolleary** [redconnect-io/node-red-contrib-mssql#2]
Hi,

we deprecated the Orion editor widget in favour of the ACE editor widget early last year. We finally removed the Orion widget entirely in 0.14.

This node needs to be updated to move over the ACE widget as it currently cannot be edited when used with 0.14.

The change is pretty straightforward; we provide a utility function for adding the editor to protect against any future changes.

Here's how our Comment node does it: https://github.com/node-red/node-red/blob/master/nodes/core/core/90-comment.html#L58

**Comment by stephenkeep** [comment]
Thanks @knolleary!

@jimturner22 could you send over a pull request?
